# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Test Jekyll site
email: pretorh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Testing/playing around with Jekyll static site generation
baseurl: "http://pretorh.github.io/test-jekyll"
url: "http://pretorh.github.io/test-jekyll"
twitter_username: pretorh
github_username:  pretorh

# Build settings
markdown: kramdown
